version: "3.1"
recipe: default.v1

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 25 # Reduced from 100 due to overfitting on a small dataset like this
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true
- name: FallbackClassifier
  threshold: 0.98  # Much higher threshold since the model is prone to overfitting
  #threshold: 0.85  # NLU fallback threshold

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 50 # Reduced from 100 due to overfitting
- name: TEDPolicy
  max_history: 5
  epochs: 30 # Reduced from 100 due to overfitting
  constrain_similarities: true
assistant_id: 20250912-201450-wide-radix